# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x02\x61\x33\"f\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x17\n\x0fpublishing_year\x18\x04 \x01(\x05\x12\x18\n\x05genre\x18\x05 \x01(\x0e\x32\t.a3.Genre\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"%\n\x12\x43reateBookResponse\x12\x0f\n\x07Message\x18\x01 \x01(\t*:\n\x05Genre\x12\x0b\n\x07\x46ICTION\x10\x00\x12\x0b\n\x07MYSTERY\x10\x01\x12\n\n\x06POETRY\x10\x02\x12\x0b\n\x07HISTORY\x10\x03\x32o\n\x10InventoryService\x12\x30\n\nCreateBook\x12\x08.a3.Book\x1a\x16.a3.CreateBookResponse\"\x00\x12)\n\x07GetBook\x12\x12.a3.GetBookRequest\x1a\x08.a3.Book\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=193
  _GENRE._serialized_end=251
  _BOOK._serialized_start=18
  _BOOK._serialized_end=120
  _GETBOOKREQUEST._serialized_start=122
  _GETBOOKREQUEST._serialized_end=152
  _CREATEBOOKRESPONSE._serialized_start=154
  _CREATEBOOKRESPONSE._serialized_end=191
  _INVENTORYSERVICE._serialized_start=253
  _INVENTORYSERVICE._serialized_end=364
# @@protoc_insertion_point(module_scope)
