# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventoryitem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13inventoryitem.proto\x12\x02\x61\x33\"o\n\x04\x42ook\x12\x18\n\x10inventory_number\x18\x01 \x01(\x05\x1a)\n\x04Item\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x08.a3.BookH\x00\x42\x07\n\x05items\"\"\n\x06status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventoryitem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=27
  _BOOK._serialized_end=138
  _BOOK_ITEM._serialized_start=61
  _BOOK_ITEM._serialized_end=102
  _BOOK_STATUS._serialized_start=104
  _BOOK_STATUS._serialized_end=138
# @@protoc_insertion_point(module_scope)
